# Generated by Django 5.2.4 on 2025-07-16 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProductCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, help_text='Si se deja vacío, se usará el nombre del producto', max_length=100, verbose_name='Título personalizado (opcional)')),
                ('custom_subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo personalizado (opcional)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Determina la posición en el carrusel (menor número = primero)', verbose_name='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, help_text='Marcar para mostrar este producto en el carrusel', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('product', models.OneToOneField(help_text='Seleccione un producto existente para mostrar en el carrusel', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto destacado')),
            ],
            options={
                'verbose_name': 'Producto Destacado',
                'verbose_name_plural': 'Carrusel de Productos Destacados',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='HomeSlider',
        ),
        migrations.AddConstraint(
            model_name='featuredproductcarousel',
            constraint=models.UniqueConstraint(fields=('product',), name='unique_featured_product'),
        ),
    ]
